// This file is generated by npm run build:icons

export type IconName =
	| 'lucide/catalog'
	| 'lucide/loop'
	| 'lucide/phone'
	| 'lucide/shopping-cart'
	| 'lucide/user'
	| 'lucide/viber'
	| 'category_korpusniDetali'
	| 'category_nasos'
	| 'category_platu'
	| 'category_accsecuari'
	| 'category_electroKlapan'
	| 'category_provoda'
	| 'category_pidoshvaUtuga'
	| 'category_korpusUtuga'
	| 'category_rezervuarVoda'
	| 'category_boiler'
