import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Suspense } from 'react'
import { Header, Loader, Sidebar } from './components'
import { ShoppingCartProvider } from './context/ShoppingCartContext'
import "./globals.css"
import PreloadedResourses from './utils/preloadedResourses'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ParoMaster",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {
  

  return (
    <html lang="uk">
      <body className={`${inter.className} primaryTextColor`}>
        <ShoppingCartProvider>
          <Suspense fallback={<Loader />}>
          <PreloadedResourses />
          <Header />
            <div className='px-8 flex items-start'>
              <Sidebar/>
              <div className='w-full'>{children}</div>
            </div>
          </Suspense>
        </ShoppingCartProvider>
      </body>
    </html>
  );
}
