import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Suspense } from 'react'
import { Header, Loader } from './components'
import BrandFilter from './components/BrandFilter'
import Category from './components/Category'
import PriceFilter from './components/PriceFilter/PriceFilter'
import Sort from './components/Sort'
import { Provider } from './components/context/Provider'
import "./globals.css"
import PreloadedResourses from './utils/preloadedResourses'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ParoMaster",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {
  

  return (
    <html lang="uk">
      <body className={`${inter.className} primaryTextColor`}>
        <Suspense fallback={<Loader />}>
           <Provider>
      <PreloadedResourses />
        <Header />
            <div className='px-8 flex items-start'>
              <div>
                <Category />
                <PriceFilter/>
                <Sort />
                <BrandFilter />
              </div>
              <div className='w-full'>{children}</div>
       
         </div>
            </Provider>
      </Suspense>
      </body>
    </html>
  );
}
