'use client';

import { useShoppingCart } from 'app/context/ShoppingCartContext';
import { createWayForPayInvoice } from 'app/lib/wayforpay';
import { Form, Formik } from 'formik';
import { useRouter } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';

import { addCustomerAction } from '@/actions/customers';
import { addOrderAction } from '@/actions/orders';
import { addUserAction } from '@/actions/users';
import PublicOfferSummary from '@/app/(public)/publicoffer/PublicOfferSummary';
import {
  IOrderedGoodSnapshot,
  sendAdminEmail,
  sendCustomerEmail,
} from '@/app/services/sendNodeMailer';
import { Breadcrumbs, Button } from '@/components/index';
import { customerFormSchema, storageKeys } from '@/helpers/index';
import { ICartItem, IOrder } from '@/types/index';
import { SessionUser, UserRole } from '@/types/IUser';
import { OrderStatus } from '@/types/orderStatus';
import { PaymentMethod } from '@/types/paymentMethod';

import { CustomerFields } from './components/CustomerFields';
import { FormEffects } from './components/FormEffects';
import OrderGood from './orderGood';

export interface ICustomerFormValues {
  name: string;
  surname: string;
  email: string;
  phone: string;
  city: string;
  warehouse: string;
  payment: PaymentMethod;
}

export interface CheckoutClient {
  user?: SessionUser;
}

const CheckoutClient: React.FC<CheckoutClient> = ({ user }) => {
  const { push } = useRouter();
  const { cart, resetCart } = useShoppingCart();

  const [isLoading, setIsLoading] = useState(false);
  const [isCheckboxChecked, setIsCheckboxChecked] = useState(false);
  const [isClient, setIsClient] = useState(false);

  const [initialValues, setInitialValues] = useState<ICustomerFormValues>({
    name: '',
    surname: '',
    email: '',
    phone: '+380',
    city: '',
    warehouse: '',
    payment: PaymentMethod.CASH_ON_DELIVERY,
  });

  const [generatedNumber, setGeneratedNumber] = useState<string | null>(null);

  useEffect(() => {
    setIsClient(true);
    setGeneratedNumber(`ORD-${Date.now()}`);

    try {
      const saved = sessionStorage.getItem(storageKeys.customer);
      if (saved) setInitialValues(JSON.parse(saved));
    } catch (err) {
      console.error(err);
    }
    // 2️⃣ Если пользователь авторизован — заполняем его данные
    if (user && user.role === UserRole.CUSTOMER) {
      setInitialValues(prev => ({
        ...prev,
        name: user.name || '',
        surname: user.surname || '',
        email: user.email || '',
        phone: user.phone || '+380',
        city: user.city || '',
        warehouse: user.warehouse || '',
        payment:
          (user.payment as PaymentMethod) || PaymentMethod.CASH_ON_DELIVERY,
      }));
    }
  }, [user]);

  const totalPrice = useMemo(
    () =>
      cart.reduce(
        (acc, item: ICartItem) =>
          acc + (item.good.price || 0) * (item.quantity || 1),
        0
      ),
    [cart]
  );

  if (!isClient) return null;

  const handleSubmit = async (values: ICustomerFormValues) => {
    if (!isCheckboxChecked)
      return toast.error('Будь ласка, погодьтесь із публічною офертою');
    if (!values.city || !values.warehouse)
      return toast.error('Будь ласка, виберіть місто та відділення');
    if (cart.length === 0) return toast.error('Кошик порожній.');

    try {
      setIsLoading(true);

      let userId: string;

      // === 1. Пользователь ===
      if (user?._id) {
        userId = user._id;
      } else {
        const userRes = await addUserAction({
          name: values.name,
          surname: values.surname,
          email: values.email,
          phone: values.phone,
          password: 'autoGenerated',
          role: UserRole.CUSTOMER,
        });

        if (userRes.message === 'Користувач вже існує') {
          // Просто продолжаем с существующим пользователем
          if (!userRes.user?._id)
            throw new Error('Не вдалося отримати існуючого користувача');

          userId = userRes.user._id;
        } else {
          if (!userRes.success || !userRes.user?._id)
            throw new Error('Не вдалося створити користувача');

          userId = userRes.user._id;
        }
      }

      // === 2. Customer ===
      const customerRes = await addCustomerAction(values);
      if (!customerRes.success || !customerRes.customer?._id)
        throw new Error('Не вдалося створити замовника');

      // === 3. Order ===
      const orderedGoods = cart.map(item => ({
        good: item.good._id,
        quantity: item.quantity,
        price: item.good.price,
      }));

      const orderData: IOrder = {
        number: generatedNumber || `ORD-${Date.now()}`,
        customer: customerRes.customer._id,
        customerSnapshot: {
          user: {
            name: values.name,
            surname: values.surname,
            phone: values.phone,
            email: values.email,
          },
          city: values.city,
          warehouse: values.warehouse,
          payment: values.payment,
        },
        orderedGoods,
        totalPrice,
        status: OrderStatus.NEW,
      };

      const orderRes = await addOrderAction(orderData);
      if (!orderRes.success) throw new Error('Не вдалося створити замовлення');

      const orderedGoodsSnapshot: IOrderedGoodSnapshot[] = cart.map(item => ({
        good: {
          _id: item.good._id,
          title: item.good.title,
          brand: item.good.brand?.name || '-',
          model: item.good.model,
          sku: item.good.sku,
        },
        quantity: item.quantity,
        price: item.good.price,
      }));

      await Promise.all([
        sendAdminEmail(orderData, orderedGoodsSnapshot),
        sendCustomerEmail(orderData, orderedGoodsSnapshot),
      ]);

      toast.success('Замовлення успішно створено! 🚀');
      resetCart();
      sessionStorage.removeItem(storageKeys.customer);
      localStorage.clear();

      if (values.payment === PaymentMethod.WAY_FOR_PAY) {
        const invoice = await createWayForPayInvoice(orderData);
        if (invoice.url) window.location.href = invoice.url;
      } else push('/');
    } catch (err) {
      console.error('Error in handleSubmit:', err);
      toast.error('Сталася помилка. Спробуйте ще раз.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="max-w-7xl mx-auto p-6">
      <Breadcrumbs />
      <div className="flex flex-col p-6 bg-white rounded-lg shadow-lg space-y-8">
        <h2 className="text-3xl font-semibold text-primary mb-4">
          Оформлення замовлення
        </h2>

        <div className="flex flex-col lg:flex-row gap-8">
          {/* Форма замовника */}
          <div className="w-full lg:w-2/3">
            <Formik<ICustomerFormValues>
              initialValues={initialValues}
              enableReinitialize
              validationSchema={customerFormSchema}
              onSubmit={handleSubmit}
            >
              {({ values, errors, touched, setFieldValue }) => (
                <Form className="flex flex-col space-y-6">
                  <FormEffects values={values} setFieldValue={setFieldValue} />
                  <CustomerFields
                    values={values}
                    errors={errors}
                    touched={touched}
                    setFieldValue={setFieldValue}
                  />
                  <div className="flex items-center space-x-2">
                    <label className="relative flex items-center cursor-pointer">
                      <input
                        type="checkbox"
                        checked={isCheckboxChecked}
                        onChange={e => setIsCheckboxChecked(e.target.checked)}
                        className="peer absolute w-0 h-0 opacity-0"
                        id="termsCheckbox"
                      />
                      <span
                        className="
        w-5 h-5 rounded border-2 border-neutral-300
        peer-checked:border-[rgb(var(--color-primaryAccentColor))]
        peer-checked:bg-[rgb(var(--color-primaryAccentColor))]
        flex-shrink-0
        transition-colors duration-200
        flex items-center justify-center
      "
                      >
                        {/* Галочка */}
                        <svg
                          className="w-3 h-3 text-white"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth={3}
                        >
                          <path
                            d="M5 13l4 4L19 7"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          />
                        </svg>
                      </span>
                      <span className="ml-2 text-[rgb(var(--color-primaryTextColor))] select-none">
                        <PublicOfferSummary />
                      </span>
                    </label>
                  </div>
                  <Button
                    type="submit"
                    label="Відправити"
                    disabled={isLoading}
                  />
                </Form>
              )}
            </Formik>
          </div>

          {/* Кошик */}
          <div className="w-full lg:w-1/3 flex flex-col gap-4">
            <h3 className="text-2xl font-semibold mb-4">Ваші товари</h3>
            {cart.length > 0 ? (
              cart.map((item: ICartItem, i) => {
                return (
                  <OrderGood
                    key={item.good._id || i}
                    good={item.good}
                    quantity={item.quantity}
                  />
                );
              })
            ) : (
              <div>Кошик порожній...</div>
            )}
            <div className="text-xl font-bold mt-4">
              Загальна сума: {totalPrice} грн
            </div>
            <p className="text-sm italic">
              {totalPrice >= 1000
                ? '🚚 Доставка безкоштовна'
                : '🚚 Вартість доставки: за тарифами перевізника'}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CheckoutClient;
